### ISSUE TITLE
Some important points

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [siimple/siimple#32] opened 2018-04-13 00:00 UTC
Hi the Siimple Community,

When I look your repository, website has few important points missing. For example, example templates for different usage situation (like blog, e-commerce, form etc.).

> I'm trying to write a example blog page using *only* Siimple.

I don't know, but what are you think for `display: flex;` because I need to use it during center all of posts. Maybe, you have some very useful class that I didn't see your documentation.

Also, I found a typo for documentation. It was Jumbotron example. You just wrote `</div<`.

Thank you

**Comment by BerkhanBerkdemir** [comment] 2018-04-13 10:01
Hi @jmjuanes 

When I read 14px, it can hard for long paragraphs. This is just my opinion for example blog. Also, I will re-edit example blog template for `display: flex;`. Actually, I started to write this repo for Jekyll :smile: 

Thank you.

**Comment by BerkhanBerkdemir** [comment] 2018-04-24 05:51
Hi @jmjuanes 

I looked your raw repo.. OK, I know, this just for showcase, but in mobile view not very useful.

Here it is the screen-shot from Firefox Desktop mobile view.

![screen shot 2018-04-23 at 22 48 25](https://user-images.githubusercontent.com/24360355/39168456-c4affd46-4748-11e8-83cb-6b4d1c063556.png)

Thank you.

**Comment by BerkhanBerkdemir** [comment] 2018-04-24 06:39
Hi @jmjuanes 

I fixed mobile view problem with added class `siimple-grid-col-sm--12`. What do you think? Is that good way to solve? [The fork](https://github.com/BerkhanBerkdemir/siimple/commit/15ed1bdbf0903f9f90444150c4d77cee5c512c3e)

Thank you.

**Comment by jmjuanes** [comment] 2018-04-24 07:34
Hi @BerkhanBerkdemir 

Yes, the test was designed for desktop but not for mobile. Adding `siimple-grid-col-sm--12` should fix this problem. Thank you!

> When I read 14px, it can hard for long paragraphs. This is just my opinion for example blog.

I have changed the default `font-size` value to `15px` and the default `line-height` to `22px`. What do you think?

**Comment by BerkhanBerkdemir** [comment] 2018-04-24 08:57
Hi @jmjuanes 

I want to answer this question according this [answer](https://ux.stackexchange.com/a/746). Well, my [blog](https://blog.berkhanberkdemir.com) `font-size` 16px, too. But, depends on the font-family, font-weight and so on.

Also, I will fix these test files (maybe, I can add fancy things :laughing: ). I just wanna ask, should we delete `siimple-menu-group` from layout.html because it doesn't fit very well with `siimple-grid-col--3` class.

> I'm just amateur CSS user. I have just ideas.

**Comment by BerkhanBerkdemir** [comment] 2018-04-24 09:37
Well, you're right. Those are just test. I will create examples after that I will send a PR.

# Example webpages

- Blog
  - Navbar
  - Header
  - Content
  - Footer
- Landing page
  - (?)
- Login form(?)
  - Email
  - Password
  - Remember me (Check-box)
  - Submit button

Also we can disable wiki page or add a home page for link to main documentation.

**Comment by BerkhanBerkdemir** [comment] 2018-04-24 20:52
Hi again @jmjuanes 

I wrote a siimple blog. Here it's [link](https://rawgit.com/BerkhanBerkdemir/siimple-blog/master/index.html)

I copied nav and jumbotron from your layout.html. I added some magic :smiley:

**Comment by jmjuanes** [comment] 2018-05-07 11:54
Hi @BerkhanBerkdemir 

I have found the bug with the form elements :smile: 

Some points about your blog example:
- Why are you using different sizes for the jumbotron and the content? The jumbotron has the `large` modifier, and the content has the `medium` modifier...
- The navbar subtitle element is available in `3.1.0`, so you should import the last beta version instead of the `3.0.0`.

Great job ;)

**Comment by BerkhanBerkdemir** [comment] 2018-05-07 23:32
@jmjuanes thank your feedback.

https://github.com/BerkhanBerkdemir/siimple-blog/blob/master/index.html#L30 I removed `large`, but when I think about `medium` it makes more sense for me because I just tried to keep articles in center.

Anyway, should I remove it too?

**Comment by jmjuanes** [comment] 2018-05-08 09:15
The problem is that you have removed the size modifer in the jumbotron component. Add the `siimple-jumbotron--medium` class ;)

Also, you should add the `siimple-navbar--medium` class to the navbar instead of the `large` modifier.

**Comment by jmjuanes** [comment] 2018-09-22 15:59
Can we close this issue? No more actions to do in the repository.

**Closed** 2018-09-22 23:01 UTC
Labels: Enhancement
