### ISSUE TITLE
Padding on fluid input makes element too wide

### ISSUE THREAD

**Issue by andreashouben** [siimple/siimple#45] opened 2018-07-29 11:53 UTC
**Describe the bug**
I created a small page using a form with a fluid input. An example can be seen here:

https://codepen.io/anon/pen/LBOBGP

I expected the fluid input to be as wide as the outer container. But it is wider.

When I remove the 10px padding on each side of the input it fits.

Am I doing something wrong? Or is this a bug?

**To Reproduce**
See codepen: https://codepen.io/anon/pen/LBOBGP

**Expected behavior**
Input as wide as outer container.

**Screenshots or Project link**
https://codepen.io/anon/pen/LBOBGP

**Desktop (please complete the following information):**
* iOs, Chrome and Firefox
* siimple@3.1.0

**Comment by jmjuanes** [comment] 2018-07-30 08:30
Hello @Guysbert . Thanks for your bug report. I have fixed it on `input` element. Also, I have fixed the same issue on other elements that have the `fluid` modifier (`select` and `textarea`).

**Comment by Guysbert** [comment] 2018-07-30 08:31
Great! When will you publish the next release? :D

**Comment by jmjuanes** [comment] 2018-07-30 21:41
I hope that tomorrow will be ready to be published :smile:

**Comment by jmjuanes** [comment] 2018-07-30 22:15
Please @Guysbert , could you check if the input in the search box of the documentation is displayed well on your device? https://docs.siimple.xyz/getting-started/installation.html

And the fluid input of the documentation? file:///Users/jmjuanes/workspace/siimple/siimple/docs/_site/form/input.html

**Comment by jmjuanes** [comment] 2018-07-31 07:37
Oops, sorry. The correct link is: https://docs.siimple.xyz/form/input.html 

Ok, so I don't know why in your codepen it looks wider and in the documentation it fits to it's parent size...

**Comment by Guysbert** [comment] 2018-07-31 07:59
On your documentation page, the browser adds the user agent stylesheet setting _box-sizing: border-box;_ 
![image](https://user-images.githubusercontent.com/3708288/43445997-fa2c407c-94a7-11e8-83cd-79e3e2611486.png)
On the codepen page it does not do that:
![image](https://user-images.githubusercontent.com/3708288/43446061-2ab5e202-94a8-11e8-8708-8e4fa04941ca.png)

After googling the issue it seems that this behaviour is caused, when `<!doctype html>` is added to the head of your page which is *not* the case on your documentation page. I guess if you'll add it, the input field will also be too wide in the documentation.

See also: 
https://stackoverflow.com/questions/7534222/what-causes-the-user-agent-stylesheet-to-use-border-box-instead-of-content

**Comment by Guysbert** [comment] 2018-07-31 08:01
I suggest to add the <!doctype html> tag to your webpage (because it's good style) and then add a box-sizing: border-box to the siimple-input--fluid class.

**Comment by Guysbert** [comment] 2018-07-31 08:05
Confirmed. This is how your page looks when you add the doctype tag:
![image](https://user-images.githubusercontent.com/3708288/43446482-4adebc24-94a9-11e8-8ffd-6e9ebefb25d3.png)

**Comment by jmjuanes** [comment] 2018-08-04 12:46
Closing issue. New version `v3.1.1` will be published in few minutes with the fix of this bug. Thank you :smile:

**Closed by jmjuanes** 2018-08-04 12:46 UTC
Labels: Type: bug
